genre_section_start_regex: "#Subreddits by genre.*"
genre_section_end_regex: "#Multi-genre & community subreddits.*"
genre_regex: "##.*"
subreddit_regex: ".*/r/.*"
save_data: true
filename_format: "{date:%Y%m%d_%H%M%S}.json"
data_folder: "data/subreddit_genre_sub_count"
test_mode: false