# Take only subreddits that fit in these specific genres on the /r/Music wiki page
genres_whitelist: ['Some decades', 'Electronic music', 'By country/region/culture', 'Other', 'Hip-hop', 'Rock/Metal', 'Any genre',]
# Exclude specific subreddits, can be useful if for example it's mainly for chat/discussion and not posting tracks
subreddit_blacklist: ['WorldMusic' , 'jambands', 'ChiefKeef', 'altrap', 'EmoScreamo', 'Drone', 'swinghouse', 'bluegrass', 'electroswing', 'composer', 'classicalmusic', 'Opera', 'Chiptunes', 'mashups', 'hiphop101', 'LofiHipHop', 'festivals', 'LetsTalkMusic', 'NameThatSong', 'IsolatedVocals', 'vocaloid',]
input_dir: "data/subreddit_genre_sub_count"
input_file: "" # if empty, pick most recent file
output_dir: "data/subreddit_playlist_mapping"
subscriber_min_count: 10000 # do not create subreddits with fewer than this number of subscribers
playlist_base_str: '/r/{} top weekly tracks'
filename_format: "{date:%Y%m%d_%H%M%S}.json"
auth_method: "client_credentials_flow"