task: "create_empty_playlists"
# Take only subreddits that fit in these specific genres on the /r/Music wiki page
genres_whitelist: ['Some decades', 'Electronic music', 'Classical music', 'By country/region/culture', 'Other', 'Hip-hop', 'Rock/Metal', 'Any genre',]
# Exclude specific subreddits
subreddit_blacklist: ['composer', 'classicalmusic', 'Chiptunes', 'mashups', 'hiphop101', 'LofiHipHop', 'festivals', 'LetsTalkMusic', 'NameThatSong', 'IsolatedVocals', 'vocaloid',]
input_dir: "data/subreddit_genre_sub_count"
input_file: "" # if empty, pick most recent file
output_dir: "data/subreddit_playlist_mapping"
subscriber_min_count: 50000 # do not create subreddits with fewer than this number of subscribers
playlist_base_str: '/r/{} top weekly tracks'
filename_format: "{date:%Y%m%d_%H%M%S}.json"