task: "get_subreddits_and_genres"
genre_section_start_regex: "#Subreddits by genre.*"
genre_section_end_regex: "#Multi-genre & community subreddits.*"
genre_regex: "##.*"
subreddit_regex: ".*/r/.*"
subscriber_min_count: 10000
save_data: false
filename_format: "subreddits-status-{date:%Y-%m-%d_%H:%M:%S}.csv"
data_folder: "data"
test_mode: true